Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('AFG', 'AF', 'AFGHANISTAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ALB', 'AL', 'ALBANIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('DZA', 'DZ', 'ALGERIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('AND', 'AD', 'ANDORRA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('AGO', 'AO', 'ANGOLA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('AIA', 'AI', 'ANGUILLA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ATG', 'AG', 'ANTIGUA AND BARBUDA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ARG', 'AR', 'ARGENTINA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ARM', 'AM', 'ARMENIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('AUS', 'AU', 'AUSTRALIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('AUT', 'AT', 'AUSTRIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('AZE', 'AZ', 'AZERBAIJAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BHS', 'BS', 'BAHAMAS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BHR', 'BH', 'BAHRAIN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BGD', 'BD', 'BANGLADESH');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BRB', 'BB', 'BARBADOS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BLR', 'BY', 'BELARUS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BEL', 'BE', 'BELGIUM');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BLZ', 'BZ', 'BELIZE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BEN', 'BJ', 'BENIN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BMU', 'BM', 'BERMUDA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BTN', 'BM', 'BHUTAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BOL', 'BO', 'BOLIVIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BIH', 'BA', 'BOSNIA AND HERZEGOVINA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BWA', 'BW', 'BOTSWANA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BRA', 'BR', 'BRAZIL');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('IOT', 'IO', 'BRITISH INDIAN OCEAN TERRITORY');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('VGB', 'IO', 'BRITISH VIRGIN ISLANDS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BRN', 'BN', 'BRUNEI DARUSSALAM');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BGR', 'BG', 'BULGARIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BFA', 'BF', 'BURKINA FASO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('BDI', 'BI', 'BURUNDI');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('KHM', 'KH', 'CAMBODIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CMR', 'CM', 'CAMEROON');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CAN', 'CA', 'CANADA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CPV', 'CA', 'CAPE VERDE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CYM', 'KY', 'CAYMAN ISLANDS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CAF', 'KY', 'CENTRAL AFRICAN REPUBLIC');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TCD', 'TD', 'CHAD');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CHL', 'CL', 'CHILE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CHN', 'CN', 'CHINA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('COL', 'CO', 'COLOMBIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('COM', 'KM', 'COMOROS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('COG', 'CG', 'CONGO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('COD', 'CG', 'CONGO, DEMOCRATIC REPLUBLIC OF');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CRI', 'CR', 'COSTA RICA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CIV', 'CI', 'C�TE D''IVOIRE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('HRV', 'HR', 'CROATIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CUB', 'CU', 'CUBA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CYP', 'CY', 'CYPRUS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CZE', 'CZ', 'CZECH REPUBLIC');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('DNK', 'DK', 'DENMARK');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('DJI', 'DJ', 'DJIBOUTI');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('DMA', 'DM', 'DOMINICA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('DOM', 'DM', 'DOMINICAN REPUBLIC');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ECU', 'EC', 'ECUADOR');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('EGY', 'EG', 'EGYPT');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SLV', 'SV', 'EL SALVADOR');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GNQ', 'GQ', 'EQUATORIAL GUINEA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ERI', 'ER', 'ERITREA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('EST', 'EE', 'ESTONIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ETH', 'ET', 'ETHIOPIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('FLK', 'FO', 'FALKLAND ISLANDS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('FJI', 'FJ', 'FIJI');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('FIN', 'FI', 'FINLAND');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('FRA', 'FR', 'FRANCE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GAB', 'GA', 'GABON');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GMB', 'GM', 'GAMBIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GEO', 'GE', 'GEORGIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('DEU', 'DE', 'GERMANY');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GHA', 'GH', 'GHANA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GIB', 'GI', 'GIBRALTAR');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GRC', 'GR', 'GREECE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GRD', 'GD', 'GRENADA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GTM', 'GU', 'GUATEMALA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GIN', 'GN', 'GUINEA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GNB', 'GW', 'GUINEA-BISSAU');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GUY', 'GY', 'GUYANA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('HTI', 'HT', 'HAITI');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('HND', 'HN', 'HONDURAS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('HKG', 'HN', 'HONG KONG (SPECIAL ADMINISTRATIVE REGION OF CHINA)');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('HUN', 'HU', 'HUNGARY');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ISL', 'IS', 'ICELAND');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('IND', 'IN', 'INDIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('IDN', 'ID', 'INDONESIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('IRN', 'IR', 'IRAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('IRQ', 'IQ', 'IRAQ');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('IRL', 'IE', 'IRELAND');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ISR', 'IL', 'ISRAEL');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ITA', 'IT', 'ITALY');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('JAM', 'JM', 'JAMAICA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('JPN', 'JP', 'JAPAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('JOR', 'JO', 'JORDAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('KAZ', 'JO', 'KAZAKHSTAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('KEN', 'KE', 'KENYA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('KIR', 'KI', 'KIRIBATI');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PRK', 'KR', 'KOREA, PEOPLE''S DEMOCRATIC REPUBLIC OF');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('KOR', 'KR', 'KOREA, REPUBLIC OF');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('XXK', 'KR', 'KOSOVO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('KWT', 'KW', 'KUWAIT');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('KGZ', 'KG', 'KYRGYZSTAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LAO', 'KG', 'LAOS, THE LAO PEOPLE''S DEMOCRATIC REPUBLIC');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LVA', 'LV', 'LATVIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LBN', 'LB', 'LEBANON');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LSO', 'LS', 'LESOTHO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LBR', 'LR', 'LIBERIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LBY', 'LR', 'LIBYA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LIE', 'LI', 'LIECHTENSTEIN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LTU', 'LT', 'LITHUANIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LUX', 'LU', 'LUXEMBOURG');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MAC', 'LU', 'MACAO (SPECIAL ADMINISTRATIVE REGION OF CHINA)');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MKD', 'MK', 'MACEDONIA, FORMER YUGOSLAV REP. OF');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MDG', 'MG', 'MADAGASCAR');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MWI', 'MW', 'MALAWI');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MYS', 'MY', 'MALAYSIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MDV', 'MV', 'MALDIVES');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MLI', 'ML', 'MALI');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MLT', 'MT', 'MALTA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MHL', 'MH', 'MARSHALL ISLANDS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MRT', 'MR', 'MAURITANIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MUS', 'MU', 'MAURITIUS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MEX', 'MX', 'MEXICO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('FSM', 'FM', 'MICRONESIA, FED.STATES OF');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MDA', 'MD', 'MOLDOVA, REPUBLIC OF');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MCO', 'MC', 'MONACO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MNG', 'MN', 'MONGOLIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MNE', 'MN', 'MONTENEGRO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MSR', 'MS', 'MONTSERRAT');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MAR', 'MA', 'MOROCCO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MOZ', 'MZ', 'MOZAMBIQUE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('MMR', 'BF', 'BURMA (UNION OF MYANMAR)');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('NAM', 'NA', 'NAMIBIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('NRU', 'NR', 'NAURU');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('NPL', 'NP', 'NEPAL');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('NLD', 'NL', 'NETHERLANDS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('NZL', 'NZ', 'NEW ZEALAND');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('NIC', 'NI', 'NICARAGUA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('NER', 'NE', 'NIGER');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('NGA', 'NG', 'NIGERIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('NOR', 'NO', 'NORWAY');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('OMN', 'OM', 'OMAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PAK', 'PK', 'PAKISTAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PLW', 'PW', 'PALAU');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PSE', 'PW', 'PALESTINIAN TERRITORY, OCC');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PAN', 'PA', 'PANAMA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PNG', 'PG', 'PAPUA NEW GUINEA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PRY', 'PY', 'PARAGUAY');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PER', 'PE', 'PERU');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PHL', 'PH', 'PHILIPPINES');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PCN', 'PH', 'PITCAIRN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('POL', 'PL', 'POLAND');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PRT', 'PT', 'PORTUGAL');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('PRI', 'PR', 'PUERTO RICO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('QAT', 'QA', 'QATAR');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ROU', 'RO', 'ROMANIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('RUS', 'RU', 'RUSSIAN FEDERATION');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('RWA', 'RW', 'RWANDA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SHN', 'RW', 'SAINT HELENA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('KNA', 'RW', 'SAINT KITTS AND NEVIS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LCA', 'RW', 'SAINT LUCIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('VCT', 'VC', 'ST VINCENT & THE GRENADINES');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('WSM', 'WS', 'SAMOA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('STP', 'ST', 'SAO TOME AND PRINCIPE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SAU', 'SA', 'SAUDI ARABIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SEN', 'SN', 'SENEGAL');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SRB', 'SN', 'SERBIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SYC', 'SC', 'SEYCHELLES');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SLE', 'SL', 'SIERRA LEONE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SGP', 'SG', 'SINGAPORE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SVK', 'SK', 'SLOVAKIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SVN', 'SI', 'SLOVENIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SLB', 'SB', 'SOLOMON ISLANDS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SOM', 'SO', 'SOMALIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ZAF', 'ZA', 'SOUTH AFRICA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SGS', 'VC', 'STH GEORGIA & SANDWICH ISL.');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ESP', 'ES', 'SPAIN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('LKA', 'LK', 'SRI LANKA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('XXC', 'VC', 'STATELESS REFUGEE OTHER');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('XXA', 'VC', 'STATELESS EXC HK/PALESTINE, 1954 CONV');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('XXB', 'VC', 'STATELESS REFUGEE 1951 CONV');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SDN', 'SD', 'SUDAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SUR', 'SR', 'SURINAME');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SWZ', 'SZ', 'SWAZILAND');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SWE', 'SE', 'SWEDEN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('CHE', 'CH', 'SWITZERLAND');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SYR', 'SY', 'SYRIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TWN', 'TW', 'TAIWAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TJK', 'TJ', 'TAJIKISTAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TZA', 'TZ', 'TANZANIA, UNITED REPUBLIC OF');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('THA', 'TH', 'THAILAND');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TLS', 'TH', 'TIMOR-LESTE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TGO', 'TG', 'TOGO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TON', 'TO', 'TONGA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TTO', 'TT', 'TRINIDAD AND TOBAGO');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TAA', 'TT', 'TRISTAN DA CUNHA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TUN', 'TN', 'TUNISIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TUR', 'TR', 'TURKEY');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TKM', 'TM', 'TURKMENISTAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('TCA', 'TC', 'TURKS AND CAICOS ISLANDS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('XXT', 'TR', 'TURKISH/REP OF NRTH CYPRUS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('UGA', 'UG', 'UGANDA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('UKR', 'UA', 'UKRAINE');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('SUN', 'UA', 'UNION OF SOVIET SOCIALIST REPUBLICS (USSR)(UNTIL 1991)');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ARE', 'AE', 'UNITED ARAB EMIRATES');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('GBR', 'GB', 'UNITED KINGDOM');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('USA', 'US', 'UNITED STATES');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('UMI', 'UY', 'US MINOR OUTLYING ISLANDS');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('URY', 'UY', 'URUGUAY');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('UZB', 'UZ', 'UZBEKISTAN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('VUT', 'VU', 'VANUATU');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('VAT', 'VU', 'VATICAN CITY');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('VEN', 'VE', 'VENEZUELA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('VNM', 'VE', 'VIETNAM');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('YEM', 'EH', 'YEMEN');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ZMB', 'ZM', 'ZAMBIA');
Insert into COUNTRY_DIR
   (COUNTRY_CODE_3, COUNTRY_CODE_2, COUNTRY_NAME)
 Values
   ('ZWE', 'ZW', 'ZIMBABWE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AP', 'IND', 'Andhra Pradesh', 'IN-AP');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AR', 'IND', 'Arunachal Pradesh', 'IN-AR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AS', 'IND', 'Assam', 'IN-AS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BR', 'IND', 'Bihar', 'IN-BR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CT', 'IND', 'Chhattisgarh', 'IN-CT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('GA', 'IND', 'Goa', 'IN-GA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('GJ', 'IND', 'Gujarat', 'IN-GJ');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HR', 'IND', 'Haryana', 'IN-HR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HP', 'IND', 'Himachal Pradesh', 'IN-HP');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('JK', 'IND', 'Jammu and Kashmir', 'IN-JK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('JH', 'IND', 'Jharkhand', 'IN-JH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('KA', 'IND', 'Karnataka', 'IN-KA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('KL', 'IND', 'Kerala', 'IN-KL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MP', 'IND', 'Madhya Pradesh', 'IN-MP');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MH', 'IND', 'Maharashtra', 'IN-MH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MN', 'IND', 'Manipur', 'IN-MN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ML', 'IND', 'Meghalaya', 'IN-ML');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MZ', 'IND', 'Mizoram', 'IN-MZ');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NL', 'IND', 'Nagaland', 'IN-NL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('OR', 'IND', 'Orissa', 'IN-OR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('PB', 'IND', 'Punjab', 'IN-PB');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RJ', 'IND', 'Rajasthan', 'IN-RJ');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SK', 'IND', 'Sikkim', 'IN-SK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TN', 'IND', 'Tamil Nadu', 'IN-TN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TR', 'IND', 'Tripura', 'IN-TR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('UT', 'IND', 'Uttarakhand', 'IN-UT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('UP', 'IND', 'UttarPradesh', 'IN-UP');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WB', 'IND', 'West Bengal', 'IN-WB');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AN', 'IND', 'Andaman and Nicobar Islands', 'IN-AN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CH', 'IND', 'Chandigarh', 'IN-CH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DN', 'IND', 'Dadra and Nagar Haveli', 'IN-DN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DD', 'IND', 'Daman and Diu', 'IN-DD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DL', 'IND', 'Delhi', 'IN-DL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LD', 'IND', 'Lakshadweep', 'IN-LD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('PY', 'IND', 'Puducherry', 'IN-PY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AL', 'USA', 'Alabama', 'US-AL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AK', 'USA', 'Alaska', 'US-AK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AZ', 'USA', 'Arizona', 'US-AZ');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AR', 'USA', 'Arkansas', 'US-AR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CA', 'USA', 'California', 'US-CA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CO', 'USA', 'Colorado', 'US-CO');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CT', 'USA', 'Connecticut', 'US-CT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DE', 'USA', 'Delaware', 'US-DE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('FL', 'USA', 'Florida', 'US-FL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('GA', 'USA', 'Georgia', 'US-GA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HI', 'USA', 'Hawaii', 'US-HI');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ID', 'USA', 'Idaho', 'US-ID');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('IL', 'USA', 'Illinois', 'US-IL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('IN', 'USA', 'Indiana', 'US-IN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('IA', 'USA', 'Iowa', 'US-IA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('KS', 'USA', 'Kansas', 'US-KS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('KY', 'USA', 'Kentucky', 'US-KY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LA', 'USA', 'Louisiana', 'US-LA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ME', 'USA', 'Maine', 'US-ME');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MD', 'USA', 'Maryland', 'US-MD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MA', 'USA', 'Massachusetts', 'US-MA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MI', 'USA', 'Michigan', 'US-MI');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MN', 'USA', 'Minnesota', 'US-MN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MS', 'USA', 'Mississippi', 'US-MS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MO', 'USA', 'Missouri', 'US-MO');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MT', 'USA', 'Montana', 'US-MT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NE', 'USA', 'Nebraska', 'US-NE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NV', 'USA', 'Nevada', 'US-NV');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NH', 'USA', 'NewHampshire', 'US-NH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NJ', 'USA', 'NewJersey', 'US-NJ');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NM', 'USA', 'NewMexico', 'US-NM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NY', 'USA', 'NewYork', 'US-NY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NC', 'USA', 'NorthCarolina', 'US-NC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ND', 'USA', 'NorthDakota', 'US-ND');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('OH', 'USA', 'Ohio', 'US-OH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('OK', 'USA', 'Oklahoma', 'US-OK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('OR', 'USA', 'Oregon', 'US-OR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('PA', 'USA', 'Pennsylvania', 'US-PA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RI', 'USA', 'RhodeIsland', 'US-RI');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SC', 'USA', 'SouthCarolina', 'US-SC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SD', 'USA', 'SouthDakota', 'US-SD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TN', 'USA', 'Tennessee', 'US-TN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TX', 'USA', 'Texas', 'US-TX');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('UT', 'USA', 'Utah', 'US-UT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('VT', 'USA', 'Vermont', 'US-VT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('VA', 'USA', 'Virginia', 'US-VA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WA', 'USA', 'Washington', 'US-WA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WV', 'USA', 'WestVirginia', 'US-WV');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WI', 'USA', 'Wisconsin', 'US-WI');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WY', 'USA', 'Wyoming', 'US-WY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DC', 'USA', 'DistrictofColumbia', 'US-DC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('GU', 'USA', 'Guam', 'US-GU');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('PR', 'USA', 'PuertoRico', 'US-PR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('UM', 'USA', 'UnitedStatesMinorOutlyingIslands', 'US-UM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('VI', 'USA', 'VirginIslands,U.S.', 'US-VI');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AS', 'USA', 'AmericanSamoa', 'US-AS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MP', 'USA', 'NorthernMarianaIslands', 'US-MP');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('11', 'CHN', 'Beijing', 'CN-11');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('50', 'CHN', 'Chongqing', 'CN-50');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('31', 'CHN', 'Shanghai', 'CN-31');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('12', 'CHN', 'Tianjin', 'CN-12');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('34', 'CHN', 'Anhui', 'CN-34');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('35', 'CHN', 'Fujian', 'CN-35');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('62', 'CHN', 'Gansu', 'CN-62');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('44', 'CHN', 'Guangdong', 'CN-44');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('52', 'CHN', 'Guizhou', 'CN-52');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('46', 'CHN', 'Hainan', 'CN-46');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('13', 'CHN', 'Hebei', 'CN-13');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('23', 'CHN', 'Heilongjiang', 'CN-23');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('41', 'CHN', 'Henan', 'CN-41');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('42', 'CHN', 'Hubei', 'CN-42');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('43', 'CHN', 'Hunan', 'CN-43');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('32', 'CHN', 'Jiangsu', 'CN-32');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('36', 'CHN', 'Jiangxi', 'CN-36');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('22', 'CHN', 'Jilin', 'CN-22');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('21', 'CHN', 'Liaoning', 'CN-21');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('63', 'CHN', 'Qinghai', 'CN-63');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('61', 'CHN', 'Shaanxi', 'CN-61');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('37', 'CHN', 'Shandong', 'CN-37');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('14', 'CHN', 'Shanxi', 'CN-14');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('51', 'CHN', 'Sichuan', 'CN-51');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('71', 'CHN', 'Taiwan', 'CN-71');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('53', 'CHN', 'Yunnan', 'CN-53');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('33', 'CHN', 'Zhejiang', 'CN-33');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('45', 'CHN', 'Guangxi', 'CN-45');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('15', 'CHN', 'Nei Mongol (mn)', 'CN-15');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('64', 'CHN', 'Ningxia', 'CN-64');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('65', 'CHN', 'Xinjiang', 'CN-65');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('54', 'CHN', 'Xizang', 'CN-54');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('92', 'CHN', 'Aomen (zh), Macao (en)', 'CN-92');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('91', 'CHN', 'Hong Kong', 'CN-91');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NSW', 'AUS', ' New South Wales', 'AU-NSW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('QLD', 'AUS', ' Queensland', 'AU-QLD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SA', 'AUS', ' South Australia', 'AU-SA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TAS', 'AUS', ' Tasmania', 'AU-TAS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('VIC', 'AUS', ' Victoria', 'AU-VIC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WA', 'AUS', ' Western Australia', 'AU-WA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ACT', 'AUS', ' Australian Capital Territory', 'AU-ACT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NT', 'AUS', ' Northern Territory', 'AU-NT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TS', 'IND', 'Telangana', 'IN-TS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BKM', 'GBR', 'Buckinghamshire', 'GB-BKM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CAM', 'GBR', 'Cambridgeshire', 'GB-CAM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CMA', 'GBR', 'Cumbria', 'GB-CMA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DBY', 'GBR', 'Derbyshire', 'GB-DBY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DEV', 'GBR', 'Devon', 'GB-DEV');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DOR', 'GBR', 'Dorset', 'GB-DOR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ESX', 'GBR', 'East Sussex', 'GB-ESX');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ESS', 'GBR', 'Essex', 'GB-ESS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('GLS', 'GBR', 'Gloucestershire', 'GB-GLS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HAM', 'GBR', 'Hampshire', 'GB-HAM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HRT', 'GBR', 'Hertfordshire', 'GB-HRT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('KEN', 'GBR', 'Kent', 'GB-KEN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LAN', 'GBR', 'Lancashire', 'GB-LAN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LEC', 'GBR', 'Leicestershire', 'GB-LEC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LIN', 'GBR', 'Lincolnshire', 'GB-LIN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NFK', 'GBR', 'Norfolk', 'GB-NFK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NYK', 'GBR', 'North Yorkshire', 'GB-NYK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NTH', 'GBR', 'Northamptonshire', 'GB-NTH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NTT', 'GBR', 'Nottinghamshire', 'GB-NTT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('OXF', 'GBR', 'Oxfordshire', 'GB-OXF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SOM', 'GBR', 'Somerset', 'GB-SOM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('STS', 'GBR', 'Staffordshire', 'GB-STS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SFK', 'GBR', 'Suffolk', 'GB-SFK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SRY', 'GBR', 'Surrey', 'GB-SRY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WAR', 'GBR', 'Warwickshire', 'GB-WAR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WSX', 'GBR', 'West Sussex', 'GB-WSX');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WOR', 'GBR', 'Worcestershire', 'GB-WOR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LND', 'GBR', 'London, City of', 'GB-LND');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BDG', 'GBR', 'Barking and Dagenham', 'GB-BDG');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BNE', 'GBR', 'Barnet', 'GB-BNE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BEX', 'GBR', 'Bexley', 'GB-BEX');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BEN', 'GBR', 'Brent', 'GB-BEN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BRY', 'GBR', 'Bromley', 'GB-BRY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CMD', 'GBR', 'Camden', 'GB-CMD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CRY', 'GBR', 'Croydon', 'GB-CRY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('EAL', 'GBR', 'Ealing', 'GB-EAL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ENF', 'GBR', 'Enfield', 'GB-ENF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('GRE', 'GBR', 'Greenwich', 'GB-GRE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HCK', 'GBR', 'Hackney', 'GB-HCK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HMF', 'GBR', 'Hammersmith and Fulham', 'GB-HMF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HRY', 'GBR', 'Haringey', 'GB-HRY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HRW', 'GBR', 'Harrow', 'GB-HRW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HAV', 'GBR', 'Havering', 'GB-HAV');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HIL', 'GBR', 'Hillingdon', 'GB-HIL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HNS', 'GBR', 'Hounslow', 'GB-HNS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ISL', 'GBR', 'Islington', 'GB-ISL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('KEC', 'GBR', 'Kensington and Chelsea', 'GB-KEC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('KTT', 'GBR', 'Kingston upon Thames', 'GB-KTT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LBH', 'GBR', 'Lambeth', 'GB-LBH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LEW', 'GBR', 'Lewisham', 'GB-LEW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MRT', 'GBR', 'Merton', 'GB-MRT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NWM', 'GBR', 'Newham', 'GB-NWM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RDB', 'GBR', 'Redbridge', 'GB-RDB');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RIC', 'GBR', 'Richmond upon Thames', 'GB-RIC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SWK', 'GBR', 'Southwark', 'GB-SWK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('STN', 'GBR', 'Sutton', 'GB-STN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TWH', 'GBR', 'Tower Hamlets', 'GB-TWH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WFT', 'GBR', 'Waltham Forest', 'GB-WFT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WND', 'GBR', 'Wandsworth', 'GB-WND');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WSM', 'GBR', 'Westminster', 'GB-WSM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BNS', 'GBR', 'Barnsley', 'GB-BNS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BIR', 'GBR', 'Birmingham', 'GB-BIR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BOL', 'GBR', 'Bolton', 'GB-BOL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BRD', 'GBR', 'Bradford', 'GB-BRD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BUR', 'GBR', 'Bury', 'GB-BUR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CLD', 'GBR', 'Calderdale', 'GB-CLD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('COV', 'GBR', 'Coventry', 'GB-COV');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DNC', 'GBR', 'Doncaster', 'GB-DNC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DUD', 'GBR', 'Dudley', 'GB-DUD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('GAT', 'GBR', 'Gateshead', 'GB-GAT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('KIR', 'GBR', 'Kirklees', 'GB-KIR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('KWL', 'GBR', 'Knowsley', 'GB-KWL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LDS', 'GBR', 'Leeds', 'GB-LDS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LIV', 'GBR', 'Liverpool', 'GB-LIV');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MAN', 'GBR', 'Manchester', 'GB-MAN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NET', 'GBR', 'Newcastle upon Tyne', 'GB-NET');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NTY', 'GBR', 'North Tyneside', 'GB-NTY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('OLD', 'GBR', 'Oldham', 'GB-OLD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RCH', 'GBR', 'Rochdale', 'GB-RCH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ROT', 'GBR', 'Rotherham', 'GB-ROT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SHN', 'GBR', 'St. Helens', 'GB-SHN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SLF', 'GBR', 'Salford', 'GB-SLF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SAW', 'GBR', 'Sandwell', 'GB-SAW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SFT', 'GBR', 'Sefton', 'GB-SFT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SHF', 'GBR', 'Sheffield', 'GB-SHF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SOL', 'GBR', 'Solihull', 'GB-SOL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('STY', 'GBR', 'South Tyneside', 'GB-STY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SKP', 'GBR', 'Stockport', 'GB-SKP');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SND', 'GBR', 'Sunderland', 'GB-SND');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TAM', 'GBR', 'Tameside', 'GB-TAM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TRF', 'GBR', 'Trafford', 'GB-TRF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WKF', 'GBR', 'Wakefield', 'GB-WKF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WLL', 'GBR', 'Walsall', 'GB-WLL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WGN', 'GBR', 'Wigan', 'GB-WGN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WRL', 'GBR', 'Wirral', 'GB-WRL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WLV', 'GBR', 'Wolverhampton', 'GB-WLV');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BAS', 'GBR', 'Bath and North East Somerset', 'GB-BAS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BDF', 'GBR', 'Bedford', 'GB-BDF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BBD', 'GBR', 'Blackburn with Darwen', 'GB-BBD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BPL', 'GBR', 'Blackpool', 'GB-BPL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BMH', 'GBR', 'Bournemouth', 'GB-BMH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BRC', 'GBR', 'Bracknell Forest', 'GB-BRC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BNH', 'GBR', 'Brighton and Hove', 'GB-BNH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BST', 'GBR', 'Bristol, City of', 'GB-BST');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CBF', 'GBR', 'Central Bedfordshire', 'GB-CBF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CHE', 'GBR', 'Cheshire East', 'GB-CHE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CHW', 'GBR', 'Cheshire West and Chester', 'GB-CHW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CON', 'GBR', 'Cornwall', 'GB-CON');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DAL', 'GBR', 'Darlington', 'GB-DAL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DER', 'GBR', 'Derby', 'GB-DER');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DUR', 'GBR', 'Durham, County', 'GB-DUR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ERY', 'GBR', 'East Riding of Yorkshire', 'GB-ERY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HAL', 'GBR', 'Halton', 'GB-HAL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HPL', 'GBR', 'Hartlepool', 'GB-HPL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HEF', 'GBR', 'Herefordshire', 'GB-HEF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('IOW', 'GBR', 'Isle of Wight', 'GB-IOW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('IOS', 'GBR', 'Isles of Scilly', 'GB-IOS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('KHL', 'GBR', 'Kingston upon Hull', 'GB-KHL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LCE', 'GBR', 'Leicester', 'GB-LCE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LUT', 'GBR', 'Luton', 'GB-LUT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MDW', 'GBR', 'Medway', 'GB-MDW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MDB', 'GBR', 'Middlesbrough', 'GB-MDB');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MIK', 'GBR', 'Milton Keynes', 'GB-MIK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NEL', 'GBR', 'North East Lincolnshire', 'GB-NEL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NLN', 'GBR', 'North Lincolnshire', 'GB-NLN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NSM', 'GBR', 'North Somerset', 'GB-NSM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NBL', 'GBR', 'Northumberland', 'GB-NBL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NGM', 'GBR', 'Nottingham', 'GB-NGM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('PTE', 'GBR', 'Peterborough', 'GB-PTE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('PLY', 'GBR', 'Plymouth', 'GB-PLY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('POL', 'GBR', 'Poole', 'GB-POL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('POR', 'GBR', 'Portsmouth', 'GB-POR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RDG', 'GBR', 'Reading', 'GB-RDG');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RCC', 'GBR', 'Redcar and Cleveland', 'GB-RCC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RUT', 'GBR', 'Rutland', 'GB-RUT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SHR', 'GBR', 'Shropshire', 'GB-SHR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SLG', 'GBR', 'Slough', 'GB-SLG');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SGC', 'GBR', 'South Gloucestershire', 'GB-SGC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('STH', 'GBR', 'Southampton', 'GB-STH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SOS', 'GBR', 'Southend-on-Sea', 'GB-SOS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('STT', 'GBR', 'Stockton-on-Tees', 'GB-STT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('STE', 'GBR', 'Stoke-on-Trent', 'GB-STE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SWD', 'GBR', 'Swindon', 'GB-SWD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TFW', 'GBR', 'Telford and Wrekin', 'GB-TFW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('THR', 'GBR', 'Thurrock', 'GB-THR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TOB', 'GBR', 'Torbay', 'GB-TOB');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WRT', 'GBR', 'Warrington', 'GB-WRT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WBK', 'GBR', 'West Berkshire', 'GB-WBK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WIL', 'GBR', 'Wiltshire', 'GB-WIL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WNM', 'GBR', 'Windsor and Maidenhead', 'GB-WNM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WOK', 'GBR', 'Wokingham', 'GB-WOK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('YOR', 'GBR', 'York', 'GB-YOR');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ANN', 'GBR', 'Antrim and Newtownabbey', 'GB-ANN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AND', 'GBR', 'Ards and North Down', 'GB-AND');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ABC', 'GBR', 'Armagh, Banbridge and Craigavon', 'GB-ABC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BFS', 'GBR', 'Belfast', 'GB-BFS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CCG', 'GBR', 'Causeway Coast and Glens', 'GB-CCG');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DRS', 'GBR', 'Derry and Strabane', 'GB-DRS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('FMO', 'GBR', 'Fermanagh and Omagh', 'GB-FMO');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LBC', 'GBR', 'Lisburn and Castlereagh', 'GB-LBC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MEA', 'GBR', 'Mid and East Antrim', 'GB-MEA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MUL', 'GBR', 'Mid Ulster', 'GB-MUL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NMD', 'GBR', 'Newry, Mourne and Down', 'GB-NMD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ABE', 'GBR', 'Aberdeen City', 'GB-ABE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ABD', 'GBR', 'Aberdeenshire', 'GB-ABD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ANS', 'GBR', 'Angus', 'GB-ANS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AGB', 'GBR', 'Argyll and Bute', 'GB-AGB');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CLK', 'GBR', 'Clackmannanshire', 'GB-CLK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DGY', 'GBR', 'Dumfries and Galloway', 'GB-DGY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DND', 'GBR', 'Dundee City', 'GB-DND');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('EAY', 'GBR', 'East Ayrshire', 'GB-EAY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('EDU', 'GBR', 'East Dunbartonshire', 'GB-EDU');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ELN', 'GBR', 'East Lothian', 'GB-ELN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ERW', 'GBR', 'East Renfrewshire', 'GB-ERW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('EDH', 'GBR', 'Edinburgh, City of', 'GB-EDH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ELS', 'GBR', 'Eilean Siar', 'GB-ELS');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('FAL', 'GBR', 'Falkirk', 'GB-FAL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('FIF', 'GBR', 'Fife', 'GB-FIF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('GLG', 'GBR', 'Glasgow City', 'GB-GLG');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HLD', 'GBR', 'Highland', 'GB-HLD');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('IVC', 'GBR', 'Inverclyde', 'GB-IVC');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MLN', 'GBR', 'Midlothian', 'GB-MLN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MRY', 'GBR', 'Moray', 'GB-MRY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NAY', 'GBR', 'North Ayrshire', 'GB-NAY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NLK', 'GBR', 'North Lanarkshire', 'GB-NLK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ORK', 'GBR', 'Orkney Islands', 'GB-ORK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('PKN', 'GBR', 'Perth and Kinross', 'GB-PKN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RFW', 'GBR', 'Renfrewshire', 'GB-RFW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SCB', 'GBR', 'Scottish Borders, The', 'GB-SCB');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ZET', 'GBR', 'Shetland Islands', 'GB-ZET');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SAY', 'GBR', 'South Ayrshire', 'GB-SAY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SLK', 'GBR', 'South Lanarkshire', 'GB-SLK');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('STG', 'GBR', 'Stirling', 'GB-STG');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WDU', 'GBR', 'West Dunbartonshire', 'GB-WDU');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WLN', 'GBR', 'West Lothian', 'GB-WLN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BGW', 'GBR', 'Blaenau Gwent', 'GB-BGW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BGE', 'GBR', 'Bridgend [Pen-y-bont ar Ogwr GB-POG]', 'GB-BGE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CAY', 'GBR', 'Caerphilly [Caerffili GB-CAF]', 'GB-CAY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CRF', 'GBR', 'Cardiff [Caerdydd GB-CRD]', 'GB-CRF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CMN', 'GBR', 'Carmarthenshire [Sir Gaerfyrddin GB-GFY]', 'GB-CMN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BW', 'DEU', 'Baden-W¸rttemberg', 'DE-BW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BY', 'DEU', 'Bavaria', 'DE-BY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BE', 'DEU', 'Berlin', 'DE-BE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('BB', 'DEU', 'Brandenburg', 'DE-BB');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HB', 'DEU', 'Bremen', 'DE-HB');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HH', 'DEU', 'Hamburg', 'DE-HH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('HE', 'DEU', 'Hesse', 'DE-HE');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MV', 'DEU', 'Mecklenburg-Western Pomerania', 'DE-MV');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NI', 'DEU', 'Lower Saxony', 'DE-NI');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NW', 'DEU', 'North Rhine-Westphalia', 'DE-NW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RP', 'DEU', 'Rhineland-Palatinate', 'DE-RP');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SL', 'DEU', 'Saarland', 'DE-SL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SN', 'DEU', 'Saxony', 'DE-SN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('ST', 'DEU', 'Saxony-Anhalt', 'DE-ST');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SH', 'DEU', 'Schleswig-Holstein', 'DE-SH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TH', 'DEU', 'Thuringia', 'DE-TH');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CGN', 'GBR', 'Ceredigion [Sir Ceredigion]', 'GB-CGN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('CWY', 'GBR', 'Conwy', 'GB-CWY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('DEN', 'GBR', 'Denbighshire [Sir Ddinbych GB-DDB]', 'GB-DEN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('FLN', 'GBR', 'Flintshire [Sir y Fflint GB-FFL]', 'GB-FLN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('GWN', 'GBR', 'Gwynedd', 'GB-GWN');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('AGY', 'GBR', 'Isle of Anglesey [Sir Ynys MÙn GB-YNM]', 'GB-AGY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MTY', 'GBR', 'Merthyr Tydfil [Merthyr Tudful GB-MTU]', 'GB-MTY');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('MON', 'GBR', 'Monmouthshire [Sir Fynwy GB-FYN]', 'GB-MON');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NTL', 'GBR', 'Neath Port Talbot [Castell-nedd Port Talbot GB-CTL]', 'GB-NTL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('NWP', 'GBR', 'Newport [Casnewydd GB-CNW]', 'GB-NWP');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('PEM', 'GBR', 'Pembrokeshire [Sir Benfro GB-BNF]', 'GB-PEM');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('POW', 'GBR', 'Powys', 'GB-POW');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('RCT', 'GBR', 'Rhondda, Cynon, Taff [Rhondda, Cynon, Taf]', 'GB-RCT');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('SWA', 'GBR', 'Swansea [Abertawe GB-ATA]', 'GB-SWA');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('TOF', 'GBR', 'Torfaen [Tor-faen]', 'GB-TOF');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('VGL', 'GBR', 'Vale of Glamorgan, The [Bro Morgannwg GB-BMG]', 'GB-VGL');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('WRX', 'GBR', 'Wrexham [Wrecsam GB-WRC]', 'GB-WRX');
Insert into STATE_DIR
   (STATE_CODE_3, COUNTRY_CODE_3, STATE_NAME, STATE_FULL_CODE)
 Values
   ('LA', 'IND', 'Ladakh', 'IN-LA');

